const PERFORMANCE_CONFIG = {
  CANVAS_BUFFER_SIZE: 2,
  TARGET_FPS: 60,
  AUDIO_PRELOAD_COUNT: 5,
  AUDIO_POOL_SIZE: 10,
  MAX_PARTICLES: 50,
  MAX_ENEMIES: 20,
  MAX_COLLECTIBLES: 30,
  GARBAGE_COLLECTION_INTERVAL: 30000,
  CLEANUP_INTERVAL: 5000,
  IMAGE_CACHE_SIZE: 100,
  SPRITE_BATCH_SIZE: 20,
  RESOURCE_TIMEOUT: 10000,
  RETRY_ATTEMPTS: 3
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = PERFORMANCE_CONFIG;
}
